### ISSUE TITLE
Crashing on 1.20.4 with sodium

### ISSUE THREAD

**Issue by Shazoi** [Noryea/motionblur-fabric#11]
When i trying load motion blur on 1.20.4 with sodium my game crashing

**Comment by Shazoi** [comment]
without sodium crashing too

**Comment by Krypion17** [comment]
Same here, heres the error if thats helpful
![image](https://github.com/Noryea/motionblur-fabric/assets/74854681/dedaff32-5d11-4c95-9f12-d1ab3dfb2a3c)
```
The game crashed whilst initializing game
Error: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_761 failed
```

**Comment by Noryea** [comment]
Sorry, this mixin failure is caused by a wrong version of satin API built in my mod. See [this post](https://www.reddit.com/r/fabricmc/comments/10558bm/error_javalangruntimeexception_mixin/?rdt=50863).

I've changed the mod structure in 1.0.3 to force users to install standalone [Satin API](https://modrinth.com/mod/satin-api), so that this issue would be fixed.

**Comment by Noryea** [comment]
If game still crashes, ask me to reopen this issue

**Comment by Krypion17** [comment]
Great, it seems to be working now. I think it would be helpful to mention satin api as a dependency in the description perhaps. Thank you for the great mod!
